# port
server:
  port: 8580

spring:
  application:
    name: product-service

  # datasource
  datasource:
    url: jdbc:h2:mem:product-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # H2
  h2:
    console:
      enabled: true

  # Flyway
  flyway:
    enabled: false

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace