version: '3.1'

services:
  db:
    image: postgres
    container_name: gateway-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: brique-gateway-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - gateway-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: gateway-adminer
    ports:
      - 8001:8080

volumes:
  gateway-volume: