version: '3.1'

services:
  db:
    image: postgres
    container_name: product-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: brique-product-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - product-volume:/var/lib/postgresql/data

volumes:
  product-volume: