# port
server:
  port: 8881

spring:
  application:
    name: offer

  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/brique-offer-db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format-sql: true

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace