# port
server:
  port: ${PORT:8480}

spring:
  application:
    name: user-service

  # datasource
  datasource:
    url: jdbc:postgresql://localhost:5433/brique-user-db
    username: user
    password: 1234

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Disable discovery
  cloud:
    discovery:
      enabled: false

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace

# Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/