# port
server:
  port: ${PORT:8480}

spring:
  application:
    name: product-service

  # datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/brique-product-db
    username: user
    password: 1234

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # H2
  h2:
    console:
      enabled: true

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace

# Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/